### ISSUE TITLE
BPMT generating wrong photo_ids

### ISSUE THREAD

**Issue by keremgure** [BuildPC/Backend#16]
The insert action from BPMT inserts the wrong photo id!

Possible Bug: `+ operator used in string concatenation, instead of int increment.`
Possible fix: `convert the string to int then do the operation.`

![photo_ids](https://user-images.githubusercontent.com/7896315/70800569-9db30100-1dbd-11ea-8eba-4255bf46f83e.png)

**Comment by DenizcanOzpinar** [comment]
The issue is solved in bpmt_v1.8. Thanks for your assistance.
