### ISSUE TITLE
[BPMT] photos upload location change

### ISSUE THREAD

**Issue by keremgure** [BuildPC/Backend#20]
Frontend now has a new subdomain **static.buildpc.software**. Therefore, all existing uploading mechanisms need to updated to fit the new schema. See BuildPC/Frontend#32 .

Please message me for details(*since the details include server information I am not disclosing them here!*) and update ASAP!

**Comment by DenizcanOzpinar** [comment]
Dear @keremgure I am very grateful for letting me now about this change.
With all respect✊ @DenizcanOzpinar
